spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/demo?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: gateway-hikariCP
      initialization-fail-timeout: 5
      validation-timeout: 3000
      leak-detection-threshold: 0
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      connection-init-sql: SET NAMES utf8mb4;
      transaction-isolation: TRANSACTION_READ_COMMITTED
      isolation-level: 4
      read-only: false
  redis:
    host: 127.0.0.1
    port: 36379
    database: 0
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 4
  cloud:
    nacos:
      serverAddr: 127.0.0.1:38848
    loadbalancer:
      nacos:
        enabled: true
  config:
    import:
      - nacos:routes.json?refreshEnabled=true
logging:
  level:
    org.springframework.http.server.reactive: debug
    org.springframework.web: trace
    org.springframework.security: trace
    org.mybatis: debug
    org.apace.ibatis: debug
    com.example: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
mybatis:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8010
jwt:
  secret: "b440c555857619a74a5f18fbf56129e237db93a23c3375a727f664479a6272c2"
  expiration: 86400000 # 示例：设置JWT有效期为一天，单位毫秒
dubbo:
  application:
    name: user-center-dubbo
  registry:
    address: nacos://127.0.0.1:38848
    protocol: nacos
  protocol:
    host: 192.168.31.169