spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: gateway-hikariCP
      initialization-fail-timeout: 5
      validation-timeout: 3000
      leak-detection-threshold: 0
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      connection-init-sql: SET NAMES utf8mb4;
      transaction-isolation: TRANSACTION_READ_COMMITTED
      isolation-level: 4
      read-only: false
  redis:
    host: 127.0.0.1
    port: 36379
    database: 0
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 4
  cloud:
    sentinel:
      eager: true
      scg:
        response-body: '{"code": 500000, "data": null, "msg": "已限流，请稍后再试"}'
        mode: response
        response-status: 500
#      datasource:
#        flow-control:
#          nacos:
#            server-addr: 127.0.0.1:38848
#            data-id: gateway-flow-rules
#            data-type: json
#            group-id: DEFAULT_GROUP
#            rule-type: gw_flow
    gateway:
      discovery:
        locators:
          - lb://
    nacos:
      serverAddr: 127.0.0.1:38848
    loadbalancer:
#      ribbon:
#        enabled: true
      nacos:
        enabled: true
  config:
    import:
      - nacos:routes.json?refreshEnabled=true
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    com.alibaba.cloud.sentinel: trace
    com.example: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
scp:
  sentinel:
    api:
      port: 38719
    dashboard:
      server: localhost:38858
dubbo:
  application:
    name: gateway-dubbo
  registry:
    address: nacos://127.0.0.1:38848
    protocol: nacos
    parameters.register-consumer-url: true
  protocol:
    host: 192.168.31.169
  consumer:
    filter: IdempotentTokenFilter